
### Create new user:
POST http://localhost:3000/register

{
  "email":"joselucas@gmail.com",
  "password":"123456789",
  "name":"joséLucasDev"
}


### Create new user:
POST http://localhost:3000/login

{
"email":"joselucas@gmail.com",
"password":"123456789",
}